version: '3'

services:
  lotto:
    build: .
    image: lotto
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis 
    volumes:
      - ~:/root
      - .:/root/src/github.com/CBarraford/lotto
    working_dir: /root/src/github.com/CBarraford/lotto
    environment:
      GOPATH: /root
      PGUSER: postgres
      PGPASSWORD: password
      PGDATABASE: db
      PGHOST: postgres
      DATABASE_URL: postgres://postgres:password@postgres:5432/db?sslmode=disable
      REDIS_URL: redis://redis:6379
      BASE_URL: http://localhost:3000

  redis:
    image: redis
    expose:
      - "6379"

  postgres:
    image: postgres:9.6.3
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
