CREATE TABLE boosts(
    id SERIAL PRIMARY KEY,
    user_id int REFERENCES users(id) ON DELETE CASCADE,
    income_id BIGINT NOT NULL DEFAULT 0, 
    multiplier INTEGER NOT NULL DEFAULT 2,
    created_time TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
