# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.8
        environment:
          - PG_HOST=localhost
          - PG_USER=ubuntu
      - image: circleci/postgres:9.6
        environment:
        - POSTGRES_USER=ubuntu
        - POSTGRES_DB=test

    working_directory: /go/src/github.com/CBarraford/lotto
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -t -d -v ./...
      - run: go vet -v ./...
      - run: go fmt ./...
      - run: go build -v ./...
      - run: go test -v ./...
        environment:
          DATABASE_URL: "postgres://ubuntu@localhost:5432/test"
