# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.8
      - image: circleci/postgres:9.4

    working_directory: /go/src/github.com/CBarraford/lotto
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -t -d -v ./...
      - run: go vet -v ./...
      - run: go fmt ./...
      - run: go build -v
      - run: go test -v
